language: node_js

node_js:
  - "8"

install:
  - npm install -g codecov
  - npm install


before_script:

script:
  - npm run jest
  - npm run build:test

after_success:
  # - codecov
  # - bash <(curl -s https://codecov.io/bash)